name: Miri

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    timeout-minutes: 5
    strategy:
      matrix:
        rust_version:
          - nightly
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}-cargo
          workspaces: >
            . -> target
      - name: Install Miri
        run: rustup component add miri
      - name: Run Miri
        run: cargo miri test
